package com.tiger.framework.datamodel;

import java.math.BigDecimal;
import java.util.Date;

public class OrderMaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_master.ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_master.ORDER_ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_master.TOTAL_MONEY
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private BigDecimal totalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_master.FREIGHT
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private BigDecimal freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_master.ORDER_STATUS
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_master.IS_DEL
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_master.ADDRESS_ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private Long addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_master.ORDER_CREATER
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String orderCreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_master.CREATED_TIME
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_master.ID
     *
     * @return the value of tb_order_master.ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_master.ID
     *
     * @param id the value for tb_order_master.ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_master.ORDER_ID
     *
     * @return the value of tb_order_master.ORDER_ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_master.ORDER_ID
     *
     * @param orderId the value for tb_order_master.ORDER_ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_master.TOTAL_MONEY
     *
     * @return the value of tb_order_master.TOTAL_MONEY
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public BigDecimal getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_master.TOTAL_MONEY
     *
     * @param totalMoney the value for tb_order_master.TOTAL_MONEY
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_master.FREIGHT
     *
     * @return the value of tb_order_master.FREIGHT
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_master.FREIGHT
     *
     * @param freight the value for tb_order_master.FREIGHT
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_master.ORDER_STATUS
     *
     * @return the value of tb_order_master.ORDER_STATUS
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_master.ORDER_STATUS
     *
     * @param orderStatus the value for tb_order_master.ORDER_STATUS
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_master.IS_DEL
     *
     * @return the value of tb_order_master.IS_DEL
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_master.IS_DEL
     *
     * @param isDel the value for tb_order_master.IS_DEL
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_master.ADDRESS_ID
     *
     * @return the value of tb_order_master.ADDRESS_ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_master.ADDRESS_ID
     *
     * @param addressId the value for tb_order_master.ADDRESS_ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_master.ORDER_CREATER
     *
     * @return the value of tb_order_master.ORDER_CREATER
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getOrderCreater() {
        return orderCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_master.ORDER_CREATER
     *
     * @param orderCreater the value for tb_order_master.ORDER_CREATER
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setOrderCreater(String orderCreater) {
        this.orderCreater = orderCreater == null ? null : orderCreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_master.CREATED_TIME
     *
     * @return the value of tb_order_master.CREATED_TIME
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_master.CREATED_TIME
     *
     * @param createdTime the value for tb_order_master.CREATED_TIME
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}