package com.pharmacodia.dg.framework.datamodel;

public class OrderAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_address.ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_address.ORDER_ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_address.NAME
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_address.PHONE
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_address.TELEPHONE
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_address.PROVINCE
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_address.CITY
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_address.COUNTRY
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_address.CONTENT
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_address.ID
     *
     * @return the value of tb_order_address.ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_address.ID
     *
     * @param id the value for tb_order_address.ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_address.ORDER_ID
     *
     * @return the value of tb_order_address.ORDER_ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_address.ORDER_ID
     *
     * @param orderId the value for tb_order_address.ORDER_ID
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_address.NAME
     *
     * @return the value of tb_order_address.NAME
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_address.NAME
     *
     * @param name the value for tb_order_address.NAME
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_address.PHONE
     *
     * @return the value of tb_order_address.PHONE
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_address.PHONE
     *
     * @param phone the value for tb_order_address.PHONE
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_address.TELEPHONE
     *
     * @return the value of tb_order_address.TELEPHONE
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_address.TELEPHONE
     *
     * @param telephone the value for tb_order_address.TELEPHONE
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_address.PROVINCE
     *
     * @return the value of tb_order_address.PROVINCE
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_address.PROVINCE
     *
     * @param province the value for tb_order_address.PROVINCE
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_address.CITY
     *
     * @return the value of tb_order_address.CITY
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_address.CITY
     *
     * @param city the value for tb_order_address.CITY
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_address.COUNTRY
     *
     * @return the value of tb_order_address.COUNTRY
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_address.COUNTRY
     *
     * @param country the value for tb_order_address.COUNTRY
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_address.CONTENT
     *
     * @return the value of tb_order_address.CONTENT
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_address.CONTENT
     *
     * @param content the value for tb_order_address.CONTENT
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}