package com.pharmacodia.dg.framework.datamodel;

public class SKU {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.id
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.product_id
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.name
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.list_price
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    private Long listPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.sale_price
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    private Long salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.stock_level
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    private Integer stockLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.id
     *
     * @return the value of sku.id
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.id
     *
     * @param id the value for sku.id
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.product_id
     *
     * @return the value of sku.product_id
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.product_id
     *
     * @param productId the value for sku.product_id
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.name
     *
     * @return the value of sku.name
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.name
     *
     * @param name the value for sku.name
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.list_price
     *
     * @return the value of sku.list_price
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public Long getListPrice() {
        return listPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.list_price
     *
     * @param listPrice the value for sku.list_price
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public void setListPrice(Long listPrice) {
        this.listPrice = listPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.sale_price
     *
     * @return the value of sku.sale_price
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public Long getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.sale_price
     *
     * @param salePrice the value for sku.sale_price
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku.stock_level
     *
     * @return the value of sku.stock_level
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public Integer getStockLevel() {
        return stockLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku.stock_level
     *
     * @param stockLevel the value for sku.stock_level
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    public void setStockLevel(Integer stockLevel) {
        this.stockLevel = stockLevel;
    }
}