package com.pharmacodia.dg.framework.dao;

import com.pharmacodia.dg.framework.datamodel.OrderAddress;
import com.pharmacodia.dg.framework.datamodel.OrderAddressExample;

import java.util.List;

public interface OrderAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_address
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_address
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    int insert(OrderAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_address
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    int insertSelective(OrderAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_address
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    List<OrderAddress> selectByExample(OrderAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_address
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    OrderAddress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_address
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    int updateByPrimaryKeySelective(OrderAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_address
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    int updateByPrimaryKey(OrderAddress record);
}