package com.pharmacodia.dg.framework.dao;

import com.pharmacodia.dg.framework.datamodel.UserAddressExample;
import com.pharmacodia.dg.framework.datamodel.UserAddress;

import java.util.List;

public interface UserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_address
     *
     * @mbggenerated Wed Jun 15 16:49:11 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_address
     *
     * @mbggenerated Wed Jun 15 16:49:11 CST 2016
     */
    int insert(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_address
     *
     * @mbggenerated Wed Jun 15 16:49:11 CST 2016
     */
    int insertSelective(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_address
     *
     * @mbggenerated Wed Jun 15 16:49:11 CST 2016
     */
    List<UserAddress> selectByExample(UserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_address
     *
     * @mbggenerated Wed Jun 15 16:49:11 CST 2016
     */
    UserAddress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_address
     *
     * @mbggenerated Wed Jun 15 16:49:11 CST 2016
     */
    int updateByPrimaryKeySelective(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_address
     *
     * @mbggenerated Wed Jun 15 16:49:11 CST 2016
     */
    int updateByPrimaryKey(UserAddress record);
}