package com.pharmacodia.dg.framework.dao;

import com.pharmacodia.dg.framework.datamodel.OrderDetail;
import com.pharmacodia.dg.framework.datamodel.OrderDetailExample;
import java.util.List;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_detail
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_detail
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_detail
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_detail
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_detail
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    OrderDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_detail
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_detail
     *
     * @mbggenerated Tue Jun 14 10:53:15 CST 2016
     */
    int updateByPrimaryKey(OrderDetail record);
}