package com.pharmacodia.dg.framework.dao;

import com.pharmacodia.dg.framework.datamodel.SKU;

import java.util.List;

public interface SKUMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    int insert(SKU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    int insertSelective(SKU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    SKU selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    int updateByPrimaryKeySelective(SKU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbggenerated Tue May 31 17:27:56 CST 2016
     */
    int updateByPrimaryKey(SKU record);

    List<SKU> listSkusByProductId(long prductId);
}